### ISSUE TITLE
Change `useModelSelector` to use reselectors

### ISSUE THREAD

**Issue by twheys** [kayak/redux-data-model#3]
The current implementation of `useModelSelector` takes a callback function to select from the store using selectors from the model. It would be a nice addition to redux-data-model to make this work a bit like reselect, so it would be possible to select memoized data from the store from a component.

Here's an example of what I'd like to be able to do:

```
const {
    loading = true,
    error,
    list,
} = useModelSelector(myModel, (state, selectors) => {
    return useMemo(() => ({
        loading: selectors.getListLoading(state),
        error: selectors.getListError(state),
        list: transformList(selectors.getList(state)),
    }), [state.model.listLoading, state.model.list]);
});
```

My model exposes a couple of selectors. I'd like to call a few of them to get all the data for my widget, and I'd like to memoize that data because I perform aa transformation on some of the selected data. I'd prefer the transform to happen here in my widget because the transformation I am doing is very specific to how I am presenting the data and I would like to keep it in the redux-store in a more generalized format.

I'm open minded about the syntax, but I think some inspiration can be draw from [reselect](https://www.npmjs.com/package/reselect).

For memoization, you need to know what values should be watched in order to know when to invalidate the memoized data. I think the selectors from the model could be used for this. The function the that is passed into `useModelSelector` returns the data that should be memoized.

Here's a proposal for how the syntax could look:
```
const {loading, error, list} = useModelSelector(
    [
        myModel.selectors.getListLoading(),
        myModel.selectors.getListError(),
        myModel.selectors.getList(),
    ],
    (loading = true, error, list) => ({
        loading,
        error,
        list: transformList(list),
    }),
);
```

`useModelSelector` should take as args a list of selectors from the model and a reselet function. It should call each of the selector values passed in as args prepend the state as the first arg, and then it should call the reselect function using the return values of the selectors as the args, and memoize the results of this function using the return values of the selectors as inputs.

Here's some other examples to demonstrate using args and also not using a reselect
```
const item = useModelSelector(
    [myModel.selectors.getDetails(id)],
    transformDetails,
);
```

```
const item = useModelSelector([myModel.selectors.getDetails(id)]);
```

**Comment by x8lucas8x** [comment]
@twheys honestly I have my doubts regarding your suggestion for the following reasons:

1. What about connectModel HOC, which doesn't support hooks? Your proposal doesn't encompass it and I'd prefer to keep things as close to redux as possible, in order to make the lib more familiar to newcomers.
2. Memoization on the component level, as you are suggesting, means it would need to be defined every time the selectors are being used in a component, which imo is counter productive, so better to keep it on model level. See https://github.com/kayak/redux-data-model/blob/master/examples/restWithNormalization/pages/index.tsx#L24 for an example of model level selector memoization.
3. I see no reason why you can't have a single selector on your widget model or equivalent, that behaves differently in the transformation step, based on a type passed as argument. A switch could address that. Or just have multiple selectors, one for each type of widget, and use the right one in the component level accordingly.
4. In my opinion explicit is better than implicit, so the way you suggest we define the selector, by no longer passing the state arg is in that sense non ideal.
6. If you are really decided your suggested hook level change are necessary, you can create a custom hook on your own codebase and keep using it, but I don't believe redux-data-model would be better off with the suggested API change.
